services:
  python:
    container_name: python_goodcoin
    image: python:3.8.18-bookworm
    volumes:
      - ./data/python:/data/python
    env_file:
      - .env
    ports:
      - "5000-5100:5000-5100"