services:
  python:
    container_name: python_goodcoin
    image: python:3.8.18-bookworm
    volumes:
      - ./data:/data/python
    environment:
      - CLIENT=1
    ports:
      - "5000:5000"

  client2: # For testing
    tty: true
    container_name: client2_goodcoin
    build:
      dockerfile: Dockerfile.test
    volumes:
      - ./data:/data/client2
    environment:
      - CLIENT=2
    ports:
      - "5001:5000"