services:
  python:
    container_name: python_goodcoin
    image: python:3.8.18-bookworm
    volumes:
      - ./data/python:/data/python
    env_file:
      - .env
    ports:
      - "5000:5000"

  client2: # For testing
    tty: true
    container_name: client2_goodcoin
    build:
      dockerfile: Dockerfile.test
    volumes:
      - ./data:/data/client2
    env_file:
      - .env
    ports:
      - "5001:5000"